In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
## Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',       
        ]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
##Define vocabulary size
voc_size = 10000

In [12]:
##One hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2957, 8761, 5520, 3242],
 [2957, 8761, 5520, 7079],
 [2957, 3344, 5520, 9715],
 [6336, 4764, 592, 2548, 3594],
 [6336, 4764, 592, 2548, 8687],
 [5752, 2957, 7508, 5520, 2600],
 [5356, 8588, 5921, 2548]]

In [15]:
##Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np


In [17]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr,padding = 'pre', maxlen = sent_length)
print(embedding_docs)

[[   0    0    0    0 2957 8761 5520 3242]
 [   0    0    0    0 2957 8761 5520 7079]
 [   0    0    0    0 2957 3344 5520 9715]
 [   0    0    0 6336 4764  592 2548 3594]
 [   0    0    0 6336 4764  592 2548 8687]
 [   0    0    0 5752 2957 7508 5520 2600]
 [   0    0    0    0 5356 8588 5921 2548]]


In [18]:
##Feature Representation
dim = 10

In [33]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_shape= (sent_length,)))
model.compile('adam','mse')

h:\DataScience\Projects\SimpleRNN\rnn\lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [34]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 516ms/step


array([[[-0.03576013, -0.03910876, -0.037248  , -0.02152562,
          0.00161231, -0.0261027 ,  0.02187899, -0.03783077,
          0.04309488, -0.04577075],
        [-0.03576013, -0.03910876, -0.037248  , -0.02152562,
          0.00161231, -0.0261027 ,  0.02187899, -0.03783077,
          0.04309488, -0.04577075],
        [-0.03576013, -0.03910876, -0.037248  , -0.02152562,
          0.00161231, -0.0261027 ,  0.02187899, -0.03783077,
          0.04309488, -0.04577075],
        [-0.03576013, -0.03910876, -0.037248  , -0.02152562,
          0.00161231, -0.0261027 ,  0.02187899, -0.03783077,
          0.04309488, -0.04577075],
        [-0.01424993, -0.00427855, -0.04513897, -0.02413107,
          0.00518524, -0.04037155,  0.02967921, -0.01844895,
         -0.0156497 , -0.01303114],
        [ 0.01438068, -0.00828253,  0.04676053,  0.00750703,
         -0.01498156, -0.01416231,  0.02284597, -0.00719998,
          0.01647378,  0.03700371],
        [ 0.04619578, -0.00091122,  0.0229468 , -0.0